#!/usr/bin/env node
/**
 * dsh-agnes-studio build post-processing.
 *
 * This package is a MERGED plugin: the Agnes Studio halves (host proxy routes +
 * the 🎬 floating panel) plus the ENTIRE `@oh-story/dsh` halves, vendored under
 * `vendor/oh-story/`, so that ONE composition row provides 短剧 / 网文 /
 * 视频解说 / 小说改游戏 全部能力.
 *
 * Two generated artifacts, both idempotent:
 *
 * 1. `lib/host-entry.js` — the host plugin entry. tsdown emits the Agnes host
 *    half at `lib/index.js` (named exports `name` / `inject` / `apply`); the
 *    vendored Oh Story host half is plain ESM at `vendor/oh-story/index.js`.
 *    Neither can simply re-export the other (both export `name`, `apply`, …),
 *    so this step writes a small composing entry that Cordis loads instead.
 *    It is what `package.json` `main` / `exports["."]` point at.
 *
 * 2. `lib/client.js` — DSH loads plugin client bundles through
 *    `window.__ModuleLoader__.load({ id, factory })`: the browser half must
 *    REGISTER a factory, not just export one. tsdown emits a bare ESM module
 *    (`export { apply, inject }`), so this step:
 *      a. concatenates the vendored Oh Story client bundle (which already
 *         registers itself as `@oh-story/dsh`) in FRONT of the Agnes one, and
 *      b. rewrites the Agnes registration so its factory pulls the Oh Story
 *         factory in through `require("@oh-story/dsh")` and composes the two
 *         apply() / inject contracts.
 *    Both registrations coexist in ONE file; the module system memoizes each
 *    factory by id and `require` resolves registered factories synchronously.
 *
 * Run after `tsdown` (see package.json "build": "tsdown && node build.mjs").
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(fileURLToPath(new URL('./package.json', import.meta.url)))
const libDir = join(root, 'lib')
const clientPath = join(libDir, 'client.js')
const hostEntryPath = join(libDir, 'host-entry.js')
const vendorClientPath = join(root, 'vendor', 'oh-story', 'client.js')

const PLUGIN_ID = 'dsh-agnes-studio'
const OH_STORY_ID = '@oh-story/dsh'
/**
 * The vendored Oh Story client half is re-registered under a PRIVATE id.
 *
 * Why: client bundles from every plugin are concatenated into ONE combo
 * script, and the module system rejects a second factory for the same id
 * ("duplicate factory registration"). If a profile still lists @oh-story/dsh
 * as its own bundle row (every instance that has not been restarted into the
 * merged world yet), a verbatim copy registering "@oh-story/dsh" would collide
 * with that row and take the whole UI down. A private id can never collide,
 * and the Agnes factory resolves it by name either way.
 */
const OH_STORY_CLIENT_ID = 'dsh-agnes-studio/oh-story'
const EXPORT_LINE = 'export { apply, inject };'

/** A source-map comment must never land mid-bundle. */
const stripMapComment = (text) => text.replace(/^\/\/# sourceMappingURL=.*$/gm, '').trimEnd()

// ═══════════════════════════════════════════════════════════════════════
// 1. Host entry — compose the Agnes half with the vendored Oh Story half
// ═══════════════════════════════════════════════════════════════════════

const hostEntry = `/**
 * GENERATED by build.mjs — do not edit by hand.
 *
 * Merged host entry for dsh-agnes-studio: the Agnes Studio half (\`./index.js\`,
 * built from src/index.ts) plus the complete vendored Oh Story half
 * (\`../vendor/oh-story/index.js\`, upstream @oh-story/dsh — untouched).
 *
 * Why a separate entry instead of an edit inside src/index.ts: the vendored
 * file must stay byte-identical to the published package (it resolves its four
 * skill trees from its OWN directory), and both halves export \`name\`/\`apply\`,
 * so composition has to happen here.
 */
import * as agnes from './index.js'
import * as ohStory from '../vendor/oh-story/index.js'

/** Agnes keeps the merged plugin's identity (fiber name). */
export const name = 'agnes-studio'

/**
 * Union of both halves' service requirements. Cordis waits for all of them
 * before apply() runs, so the Oh Story half keeps its own \`inject\` list.
 */
export const inject = Array.from(new Set([...(agnes.inject ?? []), ...(ohStory.inject ?? [])]))

/**
 * Both halves are applied to the same ctx. Failures are never swallowed: an
 * Oh Story registration error must surface as a plugin error, not silence.
 *
 * One exception, and it is load-bearing: a profile that STILL lists
 * \`@oh-story/dsh\` as its own row applies the same half twice, and the second
 * application fails the whole boot with a duplicate skill-provider error.
 * The two entries are applied concurrently, so either side can lose that race —
 * detect it before applying, and tolerate the duplicate if the race went the
 * other way. Remove the stale row to get the merged path (see README).
 */
function ohStoryProvidersPresent(ctx) {
  try {
    const providers = ctx.skills?.providers
    return providers !== undefined && typeof providers.get === 'function' && providers.get('oh-story') !== undefined
  } catch {
    return false
  }
}

export async function apply(ctx) {
  agnes.apply(ctx)
  if (ohStoryProvidersPresent(ctx)) {
    console.warn('[dsh-agnes-studio] Oh Story host half already provided by its own plugin row — skipping the duplicate registration.')
    return
  }
  try {
    await ohStory.apply(ctx)
  } catch (error) {
    if (!/already registered/u.test(String(error?.message ?? ''))) throw error
    console.warn('[dsh-agnes-studio] Oh Story host half lost the duplicate-registration race — keeping the row that won: ' + error.message)
  }
}

/** Kept for the upstream-url regression check in scripts/smoke-host.mjs. */
export { buildUpstreamUrl } from './index.js'
`

writeFileSync(hostEntryPath, hostEntry)
console.log('[dsh-agnes-studio] lib/host-entry.js composed (agnes + oh-story host halves) ✓')

// 2. Client bundle — the Agnes half only
//
// The client half used to ALSO vendor the Oh Story workbench and retarget its
// seat slot and layout anchors so the workbench could render inside the panel's
// 「✦ 创作套件」tab. That tab was withdrawn (2026-09-26) because the feature was
// not ready: the client half is just the panel again, and none of those
// build-time rewrites exist any more. The Oh Story HOST half stays vendored
// above — its skills and tools are still shipped by this plugin.
// ═══════════════════════════════════════════════════════════════════════

const src = readFileSync(clientPath, 'utf8')

if (!src.includes(EXPORT_LINE)) {
  if (src.includes('window.__ModuleLoader__.load')) {
    console.log('[dsh-agnes-studio] client.js already composed — skipping')
    process.exit(0)
  }
  console.error('[dsh-agnes-studio] build.mjs: expected "' + EXPORT_LINE + '" in lib/client.js')
  process.exit(1)
}

// Swap the module exports for a CommonJS one the loader factory can return.
const agnesBody = stripMapComment(src).replace(EXPORT_LINE, 'module.exports = { inject, apply };')

const composed =
  '// ── dsh-agnes-studio client half ────────────────────────────────────────\n' +
  'window.__ModuleLoader__.load({ id: "' + PLUGIN_ID + '", factory: (require) => {\n' +
  '  var module = { exports: {} }; var exports = module.exports;\n' +
  agnesBody +
  '\n  return module.exports;\n' +
  '} });\n'

// Guard on the text that is actually written, not on an intermediate variable:
// the withdrawn creative-suite machinery must not reappear in the bundle.
for (const forbidden of ['oh-story', 'oh_story', 'data-agnes-suite', '__ohStory']) {
  if (composed.includes(forbidden)) {
    console.error(
      '[dsh-agnes-studio] build.mjs: emitted client still references the withdrawn creative suite ("' +
        forbidden + '")',
    )
    process.exit(1)
  }
}

writeFileSync(clientPath, composed)
console.log('[dsh-agnes-studio] client.js composed (' + PLUGIN_ID + ' only) ✓')
